### ISSUE TITLE
Configuration for MM analysis

### ISSUE THREAD

**Issue by phisanti** [jeanollion/bacmman#1]
Hi,

I have recorded few movies with the mother machine and I am struggling quite a bit with the image analysis. I have tried MMhelper and this plug-in without much success. I followed the video with the instructions, so with it I am able to detect and track the microchannels. However, I cannot find a optimal configuration to track the cells. Therefore, I was wondering if you could give me some feedback on how to configure the tracking of a movie with a single fluorescent channel. Here I let you a sample movie and the current configuration that allowed me to track the microchannels. Please let me know if there is any hope!
[bacmman-config-dataset2.txt](https://github.com/jeanollion/bacmman/files/3483012/bacmman-config-dataset2.txt)

![Image_1_K_short](https://user-images.githubusercontent.com/33370667/62724917-f3406100-ba0b-11e9-95d7-c966a9402e1f.png)

**Comment by jeanollion** [comment]
Hello Phisanti, 
It is not easy to give you precise information given the only picture you posted. 
It seems the signal is highly in-homogeneous between (and within ? ) cells, which makes the detection of cells harder. Do you know what are the small fluorescent objects ? 
By seeing this picture I would advise to acquire a phase-contrast channel, or a more homogeneous fluorescent marker to get images closer to the dataset 2 or dataset 3 for instance. 
You can find information on the wiki on how to adapt configuration (using the Configuration Test tab). The paper associated with this software will  be available in the next weeks, and it may also help you. 
Good luck. 
Best Regards, Jean Ollion

**Comment by li-1-sta** [comment]
Hello,
    I can not get the meaning from bacmman output  result,would you please tell me the reason?
![image](https://user-images.githubusercontent.com/72848668/95948065-6f111700-0e22-11eb-86a7-c7a988737f9d.png)

**Comment by jeanollion** [comment]
Hello, 
The reason is this is not the output but the database file where objects are stored. To extract measurement to a csv file use the extract measurement command from the menus. Check the [wiki](https://github.com/jeanollion/bacmman/wiki) and the nature protocol paper for more detailed info. 
Best regards

**Comment by li-1-sta** [comment]
Hello,
 when I using extract measurement command,the result is the following image.I don't know what's wrong with it.
Best regards
![image](https://user-images.githubusercontent.com/72848668/99372211-d1b27280-28fa-11eb-8a0b-83895b443883.png)

**Comment by jeanollion** [comment]
Hello, This is a semicolon-separated file so you need to configure the software you use to open the file to split cells with semicolons. Apart from the header, the file is supposed to contain one line per segmented object of the object class. The fact that there are no measurements can be due to the fact there are no segmented object or that you didn't run the measurements. 
Best regards

**Comment by li-1-sta** [comment]
Hello,when I run the pre-processing and measurements command,the console showed errors as following,I don't get it.How can I find segmented object?
![image](https://user-images.githubusercontent.com/72848668/99473197-0ec34700-2985-11eb-93e7-f22b9e027e6a.png)
