### ISSUE TITLE
Segmentation bacterial cells

### ISSUE THREAD

**Issue by EdoardoBoscounipv** [jeanollion/bacmman#8]
Hello,
I'm currently working with your software on a set of mother-machine time laps videos. The images are not in phase-contrast but simple bright field so sometimes it happens to have dark zones in the middle of the channels (but still slightly brigther than the cells) which the segmentation algorithm keeps returning as cells. I thought to add a post-filter module to set a sort of threshold for the mean intensity inside the segmented region but I get an error which I cannot interprete. Could you give me some advice about it? I would really appreciate. 
Thank you so much. 

Here are one sample from the pre-proprocessed images and one from the results with the problem I mentioned (top segmented region is actually empty).

<img width="769" alt="Preprocessed" src="https://user-images.githubusercontent.com/94548684/142229658-77d9a6fc-39d0-4df6-baa2-7d24e48f9470.png">
<img width="831" alt="ResSegmTrackConErrore" src="https://user-images.githubusercontent.com/94548684/142230201-79b49bf0-2c8e-4078-9862-4d844a909924.png">

**Comment by jeanollion** [comment]
Hello Edoardo, 
Which segmentation/tracking algorithm are you using ? Can you provide  the full error stack please ? 
You may try to filter using a _TrackPostFilter_ that filter at the level of tracks; you set _PostFilter_ as filter and then _FeatureFilter_. 

If you haven't tried yet, I suggest you try [DiSTNet](https://github.com/jeanollion/bacmman/wiki/DistNet) that rely on deep learning, although the available trained weights are for phase-contrast images. If it works not so bad but not perfectly you can fine-tune it (there is a [page on the wiki](https://github.com/jeanollion/bacmman/wiki/FineTune-DistNet) for this). Otherwise, if you can generate a training set with fluorescent cells + bright-field or phase-contrast + bright-field, then it is possible to train DiSTNet. 
Best Regards
